export const GET_MOVIE_LIST = "GET_MOVIE_LIST";
export const GET_MOVIE_LIST_SUCCESS = "GET_MOVIE_LIST_SUCCESS";
export const GET_MOVIE_LIST_FAILED = "GET_MOVIE_LIST_FAILED";

export const GET_MOVIE_DETAIL = "GET_MOVIE_DETAIL";
export const GET_MOVIE_DETAIL_SUCCESS = "GET_MOVIE_DETAIL_SUCCESS";
export const GET_MOVIE_DETAIL_FAILED = "GET_MOVIE_DETAIL_FAILED";

export const GET_MOVIE_SCHEDULE = "GET_MOVIE_SCHEDULE";
export const GET_MOVIE_SCHEDULE_SUCCESS = "GET_MOVIE_SCHEDULE_SUCCESS";
export const GET_MOVIE_SCHEDULE_FAILED = "GET_MOVIE_SCHEDULE_FAILED";

export const CINEMA_SYSTEM_CODE = "CINEMA_SYSTEM_CODE";
export const GET_MOVIE_THEATER = "GET_MOVIE_THEATER";
